### ISSUE TITLE
Proposed new resize events for dialogs (floating windows)

### ISSUE THREAD

**Issue by robertdumitrescu** [node-projects/dock-spawn-ts#10]
It would be nice if we would have 3 new events for dialogs like:

onResizeStartDialog - when you engage in a resize operation (click down)
onResizeDialog - when you actually move the cursor
onResizeEndDialog - when you release the mouse and the final size is set up

**Comment by jogibear9988** [comment]
we have onSuspendLayout and onResumeLayout wich will  be called before and after the resize. if you need more, please tell.
