### ISSUE TITLE
dynamic data-panel-caption

### ISSUE THREAD

**Issue by LiIfn** [node-projects/dock-spawn-ts#12]
Hello, 
I would like to know if and how can I set the "data-panel-caption" dynamically (=bound it to my model)
thanks
l.

**Comment by jogibear9988** [comment]
I think we read it only once, so atm you need to call a method or the setter of the PanelContainer

**Comment by jogibear9988** [comment]
i'm looking to create a more web component version, this then could also observe the attributes

**Comment by LiIfn** [comment]
Thanks !
I just did this - and it works
newDocumentPanel.setAttribute("data-panel-caption", gridHeader)
