### ISSUE TITLE
dockspan-tab-handle-list-container

### ISSUE THREAD

**Issue by LiIfn** [node-projects/dock-spawn-ts#13]
Hello,
How can I set the dockspan-tab-handle-list-container on the upper side (-instead of the bottom)?

**Comment by jogibear9988** [comment]
this is not possible atm.

**Comment by jogibear9988** [comment]
Try

    .dockspan-tab-host {
        display: flex;
        flex-direction: column-reverse;
    }

**Comment by jogibear9988** [comment]
@Lilfn does it work for you like this?

**Comment by LiIfn** [comment]
Hello Jogibear,
Thank you, but it didn't help - stiil docked it to the bottom...
![image](https://user-images.githubusercontent.com/51828618/60394406-96a87700-9b2c-11e9-87f8-5b5ac7045392.png)

**Comment by LiIfn** [comment]
Hello Jogibear, 
Thanks you for the reply👍  - I had to use display: flex!**important**;
It worked, but it set the main content's tab on the bottom now
![image](https://user-images.githubusercontent.com/51828618/60394479-aeccc600-9b2d-11e9-9177-0e49baf0571f.png)

**Comment by jogibear9988** [comment]
you need to add this two:

```
.dockspan-tab-host {
    display: flex;
    flex-direction: column-reverse;
}
.document-manager > .dockspan-tab-host {
	flex-direction:column
}
```

**Comment by jogibear9988** [comment]
maybe it is also helpfull to add this also:

```
.dockspan-tab-content .panel-titlebar {
	display: none;
}
```

**Comment by LiIfn** [comment]
Thank you SO much - it worked
but I didn't add the last peace of code (-is it a must?)

**Comment by jogibear9988** [comment]
no, but then you get doubled titels for the active tab

**Comment by LiIfn** [comment]
I know - thank you ! :)

**Comment by hartum** [comment]
Thie solved the problem, but X for close dessapear :-(

**Comment by hartum** [comment]
OK, found the way _(I tried changing only the css, but it gave me problems when I stacked the tabs vertically)._

1. Locate your dock-spawn-ts code. Mine is at:
_"MyProject/node_modules/dock-spawn-ts"_

2. Edit "**FillDockContainer.js**" in
_"MyProject/node_modules/dock-spawn-ts/lib/js/FillDockContainer.js"_

3. In line 8 change
"**tabStripDirection = TabHostDirection.BOTTOM;**"
by
"**tabStripDirection = TabHostDirection.TOP;**"

4. Save (Now your tabs will be displayed on top)

5. Edit "TabHost.js" in
_"MyProject/node_modules/dock-spawn-ts/lib/js/TabHost.js"_

6. In line 19 change
"**displayCloseButton = false;**"
by
"**displayCloseButton = true;**"

7. Save (Now your tabs show close button)

8. finally add this to your CSS:
.dockspan-tab-content .panel-titlebar {
    display:none;
}

OK this is a little bit wild, it would be much better if it could be done through a configuration option, even better (better in my opinion, of course) if it were the default setting.

Enjoy
