### ISSUE TITLE
save new dock manger layout

### ISSUE THREAD

**Issue by LiIfn** [node-projects/dock-spawn-ts#14]
hello,
Is it possible to save the changed panes' positions ? If I want to have a mechanism that saves user's preferences for the layout...

**Comment by jogibear9988** [comment]
yes, ot's used in the ide sample, see https://github.com/node-projects/dock-spawn-ts/blob/master/page/demo/ide/demo.js

**Comment by LiIfn** [comment]
thanks you Jochen!
