### ISSUE TITLE
Reloading saved layout

### ISSUE THREAD

**Issue by LiIfn** [node-projects/dock-spawn-ts#15]
How can I load the json that has been saved (-of my changed layout..) using this.dockManager.saveState()
Also I would like to load this.dockManager.resumeLayout(panel)
using the build in functions - how can I do that?
thanks and have a great day for now

**Comment by jogibear9988** [comment]
does this sample not help? https://github.com/node-projects/dock-spawn-ts/blob/1a1cf95b7d942db621490f5f06046cb9ad342d72/page/demo/ide/demo.js#L27

**Comment by LiIfn** [comment]
Thank you Jochen,
Why do I need the CodeMirro? is it a must?

**Comment by jogibear9988** [comment]
> CodeMirro

What do you mean with CodeMirro???

**Comment by LiIfn** [comment]
[image: image.png]
Thank you for your response
I mean to your code here...

**Comment by jogibear9988** [comment]
Hä? I still do not understand what you mean

**Comment by LiIfn** [comment]
Danke Jochen,

1. This is what I mean  when I say CodeMirror (-that's how you called
it...):
var editor1 = *CodeMirror*(editor1_window_div, {
lineNumbers: true,
matchBrackets: true,
foldGutter: true,
gutters: ["CodeMirror-linenumbers", "CodeMirror-foldgutter"],
mode: "text/x-csrc",
value: source_steering_h,
onCursorActivity: function () {
editor1.setLineClass(editorLine1, null, null);
editorLine1 = editor1.setLineClass(editor1.getCursor().line, null, "
activeline");
}
});

*2. Also*, this code didn't work for me :(the rest worked fine, only this
function created a bug of the layout,,,)
onDock: (dockManager, dockNode) => {
console.log('onDock: ', dockManager, dockNode);
*localStorage.setItem(storeKey, dockManager.saveState());*
},

**Comment by jogibear9988** [comment]
You don't need codemirrow, it's only used in the sample

**Comment by LiIfn** [comment]
OK - *vielen Dank*!

Do you have an idea about this code that doesn't work for me...?
*2. Also*, this code didn't work for me :(the rest worked fine, only this
function created a bug of the layout,,,)
onDock: (dockManager, dockNode) => {
console.log('onDock: ', dockManager, dockNode);
*localStorage.setItem(storeKey, dockManager.saveState());*
},

**Comment by jogibear9988** [comment]
don't know. do you get a exception?

if you'd like you could also ask issues in german.

**Comment by LiIfn** [comment]
Danke!
I can't recreate it...

**Comment by LiIfn** [comment]
It Happened again - that's the only input I get:
[image: image.png]
and it reset the layout, showing only one dock panel (-instead of four=all
of them...)
Any ideas?

**Comment by jogibear9988** [comment]
I don't see an image

**Comment by LiIfn** [comment]
I see only the Document type panel and not the others...
[image: image.png]

**Comment by jogibear9988** [comment]
again no image
