### ISSUE TITLE
tabListElement in TabHost.js file - always on top

### ISSUE THREAD

**Issue by LiIfn** [node-projects/dock-spawn-ts#17]
if (this.tabStripDirection === TabHostDirection.TOP && this.tabStripDirection === TabHostDirection.BOTTOM) {
            this.hostElement.appendChild(this.tabListElement);
            this.hostElement.appendChild(this.separatorElement);
            this.hostElement.appendChild(this.contentElement);
        }
at TabHost.js
tried to define it like this - so the tabListElement will always be on the top (-and not the bottom)
with no luck...
how come?

**Comment by jogibear9988** [comment]
I do not understand your question?

What are you trying to do?

**Comment by LiIfn** [comment]
put the tubs on top and not on the botttom[image: image.png]

**Comment by LiIfn** [comment]
Also tried to set:
this.hostElement.prepend(this.tabListElement);
hostElement.insertBefore(this.tabListElement, hostElement.childNodes[0]);
in TabHost.js
but it didn't work...

**Comment by jogibear9988** [comment]
what is about the comment I wrote into: https://github.com/node-projects/dock-spawn-ts/issues/13

**Comment by jogibear9988** [comment]
solved in #13
