### ISSUE TITLE
Resizing issue with the splitbar-horizontal

### ISSUE THREAD

**Issue by mrgreen8** [node-projects/dock-spawn-ts#19]
That are still resizing issues, which is also present in the older project.  When 1st grabbing the bar to the right of the middle window (right of the Steering.cpp), the resizing glitches.  It's possibly from a resizing calculation issue.
![Capture](https://user-images.githubusercontent.com/24425251/67238823-c94be780-f41b-11e9-869e-3bd836ecca94.PNG)

**Comment by jogibear9988** [comment]
I could not reproduce this

**Comment by jogibear9988** [comment]
![Aufnahme_2019_10_22_09_52_26_927](https://user-images.githubusercontent.com/364896/67266980-b4219800-f4b1-11e9-90cb-3fe9fec4713e.gif)

**Comment by mrgreen8** [comment]
![2019-10-22-09-26-52](https://user-images.githubusercontent.com/24425251/67290535-3b6d0c80-f4ae-11e9-8022-1a88f9be256b.gif)

**Comment by mrgreen8** [comment]
I'm a full time Dev, and it seems to be an existing issue.  From my testing, both dock-spawn and dock-spawn-ts have this issue.  Here are some of my browser specs when this issue occurs:

Google Version 77.0.3865.120 (Official Build) (64-bit)
window.outerHeight: 750
window.outerWidth: 1397
window.innerHeight: 679
window.innerWidth: 1397

This is probably one of the best projects for javascript window/panel docking.  If I can help you with this issue, or the other issue that I posted, please let me know.

**Comment by mrgreen8** [comment]
![image](https://user-images.githubusercontent.com/24425251/67304487-e89d5000-f4c1-11e9-89da-aa663f9b63fa.png)

**Comment by mrgreen8** [comment]
![image](https://user-images.githubusercontent.com/24425251/67304638-21d5c000-f4c2-11e9-9a22-621ea1db2da3.png)

**Comment by mrgreen8** [comment]
The problem with the resizing seems to be in the calculations.  When I had this issue, the two splitter-container-horizontal frames and the splitbar-vertical widths had a total width that was higher than my window.innerWidth:

splitter-container-horizontal width: 148px (left panel)
splitbar-vertical width: 5px (middle bar)
splitter-container-horizontal width: 881px (right panel)
**Total Width: 1034px
window.innerWidth: 1033px**

**Work Around:** go to the docker-manager.css file and reduce the splitbar-vertical width to 4px.
**Solution:** Update the calculation(s) that are being used for the resizing, so the splitbar-vertical width can be adjusted.

I might look more into this to see if I can figure out where in the code this issue is happening.  It might be something simple, such as just rounding down.

**Comment by mrgreen8** [comment]
My laptop screen might have been the perfect size to cause this issue. :)

**Comment by jogibear9988** [comment]
I still could not reproduce...
Do you use a custom css? I also could change the spliterbar size ant it still works

**Comment by mrgreen8** [comment]
When the issue occurred, I was using your project CSS.

**Comment by mrgreen8** [comment]
Seems to be an issue going back to the original source code of dock-spawn.

**Comment by jogibear9988** [comment]
means? I can close?

**Comment by mrgreen8** [comment]
The issue still exists, so it needs to remain open until resolved.  I've been checking into it.  Maybe I can find a fix.

**Comment by jogibear9988** [comment]
with my source or original one?

**Comment by jogibear9988** [comment]
i could only reproduce if I change the spliterwidth via chrome debugger, but it‘s fixed after a window resize.
so dynamic splitter width is not supported

**Comment by mrgreen8** [comment]
I believe this is coming from the original source.  It was happening with the another version, and with your es5 compiled version.

In Google Chrome Version 78.0.3904.70 (Official Build) (64-bit), when the window.innerWidth is a negative number, after grabbing and moving the split bar to the right of the middle window (right of the Steering.cpp), the resizing glitches in the browser.  It seems like there is a calculation issue, which is causing the wrapping in Chrome 75.  

On the machine with the issue, it works in Microsoft Edge 44.18362.387.0.  I tested on another machine that has Google Chrome Version 75.0.3370.142 (Official Build) (64-bit) and it works.  However, I didn't check the element calculations on those tests.

This is possibly a browser issue.  I reported it to Google.

**Comment by maximkarapysh** [comment]
> I believe this is coming from the original source. It was happening with the another version, and with your es5 compiled version.
> 
> In Google Chrome Version 78.0.3904.70 (Official Build) (64-bit), when the window.innerWidth is a negative number, after grabbing and moving the split bar to the right of the middle window (right of the Steering.cpp), the resizing glitches in the browser. It seems like there is a calculation issue, which is causing the wrapping in Chrome 78.
> 
> On the machine with the issue, it works in Microsoft Edge 44.18362.387.0. I tested on another machine that has Google Chrome Version 75.0.3370.142 (Official Build) (64-bit) and it works. However, I didn't check the element calculations on those tests.
> 
> This is possibly a browser issue. I reported it to Google.

Found a solution to the problem?
The same error appears, only in Chrome (Firefox and Edge work well)

**Comment by mrgreen8** [comment]
No solution as of right now. What version of Google Chrome are you using?

**Comment by maximkarapysh** [comment]
Google Chrome Version 80.0.3987.122 (Official Build) (64-bit)

Sometimes it works fine in chrome, sometimes not.

I also noticed a similar incorrect behavior with zoom.
![bandicam-2020-03-03-18-56-31-296](https://user-images.githubusercontent.com/18233313/75799862-62531d80-5d81-11ea-902b-1eedeaf50b58.gif)

**Comment by mrgreen8** [comment]
With the Google Chrome version 78 that I was using, it seemed to happen when the browser view window (viewport) had an odd number for the width.
