### ISSUE TITLE
How to Use Documentation

### ISSUE THREAD

**Issue by mrgreen8** [node-projects/dock-spawn-ts#21]
www.dockspawn.com is no longer working, and I've visited your webpage of https://node-projects.github.io/dock-spawn-ts/.  Is there anywhere else to find some documentation on how to use this project?  Like instructions of how to set a docked panel, so it can't be undocked.

**Comment by jogibear9988** [comment]
I don't think this is possible at the moment to lock the panel so it cannot be undocked!

**Comment by mrgreen8** [comment]
I found how to set all docked panels to be undockable (not allowed to become a floating dialog), but not for a single panel (didn't test floating with that).  I added some code, and I'm able to do it now for a single panel.

Are you still working on this project?  Would you like for me to maybe help you update this?

**Comment by jogibear9988** [comment]
@mrgreen8 do you still need help?
