### ISSUE TITLE
Restrict Panel Movement to Specific Boundaries

### ISSUE THREAD

**Issue by Arj4ns** [node-projects/dock-spawn-ts#23]
Is there a way to restrict panel movement to a set of defined boundaries? 

Like for an example, lets say I have a box on the screen, with a panel inside of it. When I move the panel, I can move it around freely like normal, however, I will not be able to move it outside of the box. I would only be able to move it within the boundaries of the box.

**Comment by jogibear9988** [comment]
try my last commit, 

youn need to supply "moveOnlyWithinDockConatiner" in the config

**Comment by Arj4ns** [comment]
Alright, I'll give that a shot.

**Comment by jogibear9988** [comment]
maybe it's a little bit buggy... we need to look what needs to be fixed
