### ISSUE TITLE
Cannot re-open floating dialog

### ISSUE THREAD

**Issue by Arj4ns** [node-projects/dock-spawn-ts#24]
This may be a bug, I'm not too sure, but if you know of a way to work around it, please let me know.

I wanted to make a button that adds a panel back onto the screen after you close it. This seems to work fine if the panel is added to one of the docks (ex. docked on the left, right, etc). You can close it with the x button in the corner and reopen it by calling the same dockLeft, dockRight, etc command. I assume this is because when you close the node, it isn't actually destroying it?

Regardless, if you build a panel with floatDialog, close the panel, and then try to reopen it with the same floatDialog command, it just doesn't do anything. The element returns null, and a panel is not created.

Interestingly enough, if you dock the floating panel and then close it,  you are able to reopen it with the same command. It does not work if you dock the panel, undock it, and then close it though.

Do you know of any work around for this?

It also might be because of how I'm checking to see if their panel already exists on the screen. Right now, it seems that when the panel has been closed, using getElementById on it returns null. 
Here's my code for a basic add:

`    function toggleTools(){
        console.log(document.getElementById("tools"));
        if(document.getElementById("tools") == null){
            dockManager.floatDialog(tools, 50, 50);
        }
    }`

**Comment by Arj4ns** [comment]
Never mind, it appears I was able to get around it by changing PanelContainer.js's close() method. In particular, I changed the line this.floatingDialog.remove() to this.floatingDialog.close()

This was line 267 for me.

**Comment by jogibear9988** [comment]
I‘ll look that this works in my repo too
