### ISSUE TITLE
Panels shrink or expand when another panel is docked

### ISSUE THREAD

**Issue by Arj4ns** [node-projects/dock-spawn-ts#25]
I've noticed this issue when I dock new panels onto the screen. Its something that occurs with existing panels as well though. When docking the panels, like, say, on the right, I'd expect all the panels to shrink in order to make space for the new panel. However, this doesn't really happen. Instead the panels act strange, and they might expand or shrink. 

Take this example on the IDE demo
![resizing_issue](https://user-images.githubusercontent.com/26260220/70745567-daf19300-1cd8-11ea-9017-015fa23119eb.gif)

Repeatedly putting this panel into the same place shrinks the panel itself. 
Is there a way to set it as a steady number? Like make it always take up half the space?

**Comment by jogibear9988** [comment]
Not yet... I'll look next week what I'll can implement.

atm a the size of the dialog is somehow used in the callculation...

**Comment by jogibear9988** [comment]
Maybe you'd like to join the org and help to work on the project?

**Comment by Arj4ns** [comment]
No time i'm afraid. But if I find anything while using this, I'll make sure to drop it here.

**Comment by jogibear9988** [comment]
@Arj4ns I've worked on this. Could you try again, this should be fixed.
