### ISSUE TITLE
Escape button is closing focused pane

### ISSUE THREAD

**Issue by LiIfn** [node-projects/dock-spawn-ts#26]
Hello,
While clicking on a pane\document in the dock manager and afterwards on the escape button the pane get closed
How can I prevent it?
thanks
l.

**Comment by jogibear9988** [comment]
escClosesWindow in DockConfig

**Comment by LiIfn** [comment]
Thank you Jochen 
Where can I find it?

**Comment by LiIfn** [comment]
Vielen Dank Jochen !

**Comment by LiIfn** [comment]
I tried It:
export class DockConfig {
    constructor() {
        this.escClosesWindow = false;
    }
}
but it's still closing the panes... 
What am I missing?

**Comment by jogibear9988** [comment]
you need to hand over a dockConfig instance to the dockspawn constructor

**Comment by jogibear9988** [comment]
like here https://github.com/node-projects/dock-spawn-ts/blob/c9aa1a38640cb5b1edd80b7217f16fb77615fc64/page/demo/demo_2.html#L35

**Comment by jogibear9988** [comment]
@LiIfn does it work?

**Comment by LiIfn** [comment]
Yes Jochen  :)
Vielen Dank !

**Comment by jogibear9988** [comment]
nächstes msl: schließen 😊
