### ISSUE TITLE
nodes' dock-spawn-ts issue

### ISSUE THREAD

**Issue by LiIfn** [node-projects/dock-spawn-ts#30]
Hello, and thanks again for this amazing dock-spawn-ts' project!

I can't really point it out but every once in a while, I get this error message and I can't run my project - Can you tell me the reason for this? Or maybe you could suggest to me how to handle this? or what is missing...

![image](https://user-images.githubusercontent.com/51828618/81554373-5726fa00-938f-11ea-8f1e-96c0b1563f8c.png)
 
Thank you,
l.

**Comment by jogibear9988** [comment]
No.
Can't you tell how I could reproduce?

**Comment by LiIfn** [comment]
Thank you Jochen Kühner
There was unnecessary File named "webcomponent" that caused it - Since I removed it I don't get this error anymore...
Danke viel mal
