### ISSUE TITLE
Doing Tab splitting (vertical/horizontal)

### ISSUE THREAD

**Issue by dinobot71** [node-projects/dock-spawn-ts#32]
Hi, we're using this with an Angular 9 project to create a genuine cloud based IDE...dock spawn was an awesome accelerator, thanks for this project! :)  

But...I'm not sure how to properly do tab splitting, like if I have two tabs open...and I just want to drag one of them to be beside the other so I can view both at the same time, or one below the other, again to see both at the same time...it works...but the one I drag...is no longer tabbed. :( 

Style gets messed up a bit and I can't close that one :(  I guess what its implying is that when I drag a tab, I want it dock with another document manager now just the general top/down/left/right node.  

How can I force the landing to become a tabbed window?  I think I might be able to do it in initialization of the document window...but not sure, if you can give any pointers here it would be greatly appreciated.   Being able to view tab content at the same time would be super valuable for us.

**Comment by dinobot71** [comment]
I think I have a plan of attack on this one; instead of trying to be all automatic, maybe just have a vertical / horizontal split action in the main menu bar, which would programmatically split the main document area and move the tab currently selected to to the new empty panel in dockFill() mode...so that its a tab, and you could then presumably drag other tabs to it if you wanted.

I think should probably work, I'm pretty sure there are methods on DockNode etc for adding children and re-parenting.  

I'll take a shot at doing it that way and report back :)

**Comment by jogibear9988** [comment]
Don't know what you mean here.

**Comment by dinobot71** [comment]
Here is a quick screen shot of an example menu action for editor tabs; in InteliJ:

![tab-splitter-actioin](https://user-images.githubusercontent.com/18564924/84970164-205ba680-b0e8-11ea-8bd1-b9db130575e6.png)

The action is clone the current editor tab...but in a pane below the current group of editor tabs...so that you can view two different locations...at the same time...

![split-tabs](https://user-images.githubusercontent.com/18564924/84970314-6a448c80-b0e8-11ea-9150-b9d2c71df4b1.png)

maybe its the same file -- like above, when you first split...but you could add other tabs and be looking at two different files...at the same time :)

So the general use case is; how to "split" the current main group of tabs...into two groups of tabs? 

Right now, if I drag a tab away from the main group of tabs in Dock Spawn TS...then I have to drop it in the North, South, East or West locations...which are not groups of tabs :(   So it works...but..once I've moved the tab...it becomes a regular panel.  I'm just looking to have it be another group of tabs :)

Like, lets say I dragged the tab to the South position (in the home page example its the output panel)...can make the output panel *also* be a tab group?

**Comment by jogibear9988** [comment]
I don't think we need to split tabs. You need to dock beside of the current document container.

If you do this by code and dock with 0.5 it should work.

like this:


           let newNode = dockManager.dockLeft(documentNode, solution, 0.50);

**Comment by jogibear9988** [comment]
problem atm. is we do not differ between documents and other windows (I started this by introducting Paneltype).
If you look in VS you cannot dock documents to tool containers and also not the other way around.

Maybe we could work on this.

**Comment by dinobot71** [comment]
got it, ok, let me give it some thought and see what I can do.  I've got a dead line on Monday so I can't look at it right away, but this is a feature I'm definitely looking for, I'll circle back to this next week.  stay tuned...
