### ISSUE TITLE
Resize Cracking

### ISSUE THREAD

**Issue by dinobot71** [node-projects/dock-spawn-ts#33]
Hi we're using dock spawn ts in an Angular 9 project, to make a genuine cloud based IDE...its working great, thanks!  But, when we change the size of panes internally, like by closing a pane or dragging a pane slider...the overall "resize" isn't always called, and the layout "cracks",  it leaves gaps and you can see the background behind the dock manager. 

There is a simple work around...I just resize the browser itself, and that seems to always force a resize of all the panels as needed, and the gaps disappear.  But...would be much better if there was a way to ensure the dock spawn panels always update resizing when the size of any internal pane changes.  maybe I did something wrong in initialization, or didn't register all the needed resize callbacks or something?  

If you can give some pointers on that or suggest things I can try, would be greatly appreciated.  Thanks again for this project, its a great head start on the whole dockable windows thing.

**Comment by dinobot71** [comment]
Just wanted to add I can potentially try to find hours to help out with this project, not sure if you're taking on members or not tho.

**Comment by jogibear9988** [comment]
You can fix this maybe by using a ResizeObserver for the main div.

https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver

And call the same code as for the window resize.

**Comment by dinobot71** [comment]
Thanks for the tip!  Yes, it wasn't actually to do with Dock Spawn TS; the content <divs> inside the panesl were all resizing as they should, but...my three.js viewer had canvas's that were not being updated...so on each viewer I added a self watcher using the ResizeObserver; so that when its surrounding <div> changes...the canvases get updated and three.js stays completely in sync with the panel size :)

There was one other minor issue; my canvases were sometimes shrinking about 15px smaller than the panel on the right side and the bottom size...which seems a lot like space left for scroll bars, so I clamped "overflow: hidden" on the container for three.js...and now everything stays absolutely in sync from border to border of the panel even when I hammer it with sliding and opening and closing panels around the document manager.

Fully resolved :)

**Comment by jogibear9988** [comment]
@dinobot71 I've invited you
