### ISSUE TITLE
Disabling panel resizing

### ISSUE THREAD

**Issue by Pryanishnik** [node-projects/dock-spawn-ts#34]
Is it possible to disable resizing of a specific panel?

**Comment by jogibear9988** [comment]
not at the moment.
how should it work? at the moment panels resize also when something is docked.
Or do you mean a dialog?

**Comment by Pryanishnik** [comment]
let's take an example of IDE. I.E. bottom panels (output and problems) might be with fixed vertical size. so, you can not move splitter between editor and bottom panels (just my idea how it can be). Might be useful when you want to limit your UI for end user  with some "locked" pre-designed things

**Comment by jogibear9988** [comment]
Yes, could be usefull.
Atm. I've no time to implement this. But if you could create a pull req, I can look to merge.
