### ISSUE TITLE
getting unnecessary white space between grid columns while sizing the panel

### ISSUE THREAD

**Issue by nareshsuda** [node-projects/dock-spawn-ts#37]
[sample-ifix-project.zip](https://github.com/node-projects/dock-spawn-ts/files/5134221/sample-ifix-project.zip)
node modules to be downloaded after downloading the sample project
![image](https://user-images.githubusercontent.com/40139419/91394847-5cce2000-e858-11ea-9d2e-7d2fcbac4f75.png)

**Comment by jogibear9988** [comment]
do you habe a online sampe? 
maybe on jsbin or a similar page?

**Comment by nareshsuda** [comment]
no, do we have event line onPanelresize ?
