### ISSUE TITLE
Open own context menu for TabHandle

### ISSUE THREAD

**Issue by DennisRuss** [node-projects/dock-spawn-ts#41]
Hello, 

Is there an easy way to override the default context menu of a TabHandle?

I create a new Panel like this:
`let messageDetail = new PanelContainer(document.getElementById("testComponent"), this.dockManager, PanelType.panel);
`
And override the contextmenu:
`
        messageDetail.elementTitle.addEventListener('contextmenu', this.oncontextMenuClicked.bind(messageDetail.containerElement));`
This works fine.

But as soon as I dock the Panel to the "main" dock-node, i only have the TabHandles, where i could call my own context menu from.
It currently always shows the options "Close all documents" and "Close all documents but this".
Is it possible to override this contextmenu?

Regards.

**Comment by jogibear9988** [comment]
TabHandle.createContextMenuContentCallback = (tabHandle: TabHandle, contextMenuContainer: HTMLDivElement, documentMangerNodes: DockNode[]) => {
            const btnCloseAll = document.createElement('div');
            btnCloseAll.innerHTML = '<t-t>STD_CloseAllTabs</t-t>';
            contextMenuContainer.append(btnCloseAll);

            const btnCloseAllButThis = document.createElement('div');
            btnCloseAllButThis.innerHTML = '<t-t>STD_CloseAllTabsButNotThis</t-t>';
            contextMenuContainer.append(btnCloseAllButThis);

            const btnNewBrowserTab = document.createElement('div');
            btnNewBrowserTab.innerHTML = '<t-t>STD_OpenInNewBroserTabs</t-t>';
            contextMenuContainer.append(btnNewBrowserTab);

            const btnNewBrowserTabFull = document.createElement('div');
            btnNewBrowserTabFull.innerHTML = '<t-t>STD_OpenInNewBroserTabsFull</t-t>';
            contextMenuContainer.append(btnNewBrowserTabFull);

            const btnNewBrowserTabFullNoDock = document.createElement('div');
            btnNewBrowserTabFullNoDock.innerHTML = '<t-t>STD_OpenInNewBroserTabsFullNoDock</t-t>';
            contextMenuContainer.append(btnNewBrowserTabFullNoDock);

            const btnNewBrowserTabTouch = document.createElement('div');
            btnNewBrowserTabTouch.innerHTML = '<t-t>STD_OpenInNewBroserTabsTouch</t-t>';
            contextMenuContainer.append(btnNewBrowserTabTouch);

            btnCloseAll.onclick = () => {
                const length = documentMangerNodes.length;
                for (let i = length - 1; i >= 0; i--) {
                    const panel = <PanelContainer>documentMangerNodes[i].container;
                    if (panel.panelType == PanelType.document) {
                        panel.close();
                    }
                }
                tabHandle.closeContextMenu();
            };

            btnCloseAllButThis.onclick = () => {
                const length = documentMangerNodes.length;
                for (let i = length - 1; i >= 0; i--) {
                    const panel = <PanelContainer>documentMangerNodes[i].container;
                    if (tabHandle.parent.container != panel && panel.panelType == PanelType.document) {
                        panel.close();
                    }
                }
                tabHandle.closeContextMenu();
            };

            btnNewBrowserTab.onclick = () => {
                //@ts-ignore
                const url = (<PanelContainer>tabHandle.parent.container).elementContent.mccurl;

                if (url) {
                    const win = window.open(url, '_blank');
                    win.focus();
                }
                tabHandle.closeContextMenu();
            };

            btnNewBrowserTabFull.onclick = () => {
                //@ts-ignore
                const url = (<PanelContainer>tabHandle.parent.container).elementContent.mccurl + '&hideMessageWindow&hideMenu&hideHeader';

                if (url) {
                    const win = window.open(url, '_blank');
                    win.focus();
                }
                tabHandle.closeContextMenu();
            };

            btnNewBrowserTabFullNoDock.onclick = () => {
                //@ts-ignore
                const url = (<PanelContainer>tabHandle.parent.container).elementContent.mccurl + '&hideMessageWindow&hideMenu&hideHeader&hideDockHeader';

                if (url) {
                    const win = window.open(url, '_blank');
                    win.focus();
                }
                tabHandle.closeContextMenu();
            };

            btnNewBrowserTabTouch.onclick = () => {
                //@ts-ignore
                const url = (<PanelContainer>tabHandle.parent.container).elementContent.mcctouchurl;

                if (url) {
                    const win = window.open(url, '_blank');
                    win.focus();
                }
                tabHandle.closeContextMenu();
            };
        };
    }

**Comment by jogibear9988** [comment]
does this help?

**Comment by DennisRuss** [comment]
Holy ****. 
How blind was I to not see the `TabHandle.createContextMenuContentCallback`...

Open the Panel in a new browser-tab was exactly what i wanted to do.
Thank you very much.
