### ISSUE TITLE
error while debugging on chrome developer tools

### ISSUE THREAD

**Issue by gitmahmoud** [node-projects/dock-spawn-ts#48]
![image](https://user-images.githubusercontent.com/49977815/124380758-c7dd5400-dcbe-11eb-9dfa-b7a1dbb41c4d.png)

![image](https://user-images.githubusercontent.com/49977815/124380776-f5c29880-dcbe-11eb-9ec7-ec732182ed5f.png)

![image](https://user-images.githubusercontent.com/49977815/124380801-1ee32900-dcbf-11eb-92e0-263d90ef57dc.png)

**Comment by jogibear9988** [comment]
I could not reproduce this
