### ISSUE TITLE
Resize bug in the IDE Demo

### ISSUE THREAD

**Issue by chyj4747** [node-projects/dock-spawn-ts#49]
https://node-projects.github.io/dock-spawn-ts/page/demo/ide/demo.html

When resizing the Toolbox, you will see the bug.

Btw, after resizing the Solution Explorer, the bug view will be fixed.

I'm using Chrome.

**Comment by jogibear9988** [comment]
I don't get what bug you mean...

**Comment by chyj4747** [comment]
> I don't get what bug you mean...

The bug didn't appear in your broswer? It's very easy to reproduce the bug by resizing the width of the Toolbox.

When resizing the Toolbox which is on the righ side, the panes at buttom will also move and left an empty area.

**Comment by jogibear9988** [comment]
I don't know what you mean... 

Chrome:
https://watch.screencastify.com/v/DxM6GNJozysDWvfeBtCv

I also tested Safari & Firefox, no problems

**Comment by jogibear9988** [comment]
maybe you hav set up some browser styles. Or an extension ?

**Comment by chyj4747** [comment]
![DockSpawn Bug](https://github.com/chyj4747/for-show-pics-in-git/blob/main/DockSpawn%20bug.gif?raw=true)
[the gif is here](https://github.com/chyj4747/for-show-pics-in-git/blob/main/DockSpawn%20bug.gif)

Well it's actually not necessary to drag the border so fast, the bug always happen in my chrome(version 92.0.4515.131, 64 bit). No browser style and I already turned off all extensions.

I also tested in Firefox. The demo works fine.

So it seems to be a chrome related bug?

Also I got an error `Error with Permissions-Policy header: Unrecognized feature: 'interest-cohort'.`, which should have nothing to do with the bug.

**Comment by jogibear9988** [comment]
As i said, I could not reproduce. So I don't know how I could fix.
I also use chrome, but bug does not happen on my system.

With dev tools open, it's also slow on my system. But this also happens for example with WcDocker. Don't think this is a bug, I think it's about the massive relayouting that happens....

**Comment by jogibear9988** [comment]
could not reproduce...

Maybe you had zoom in browser active?

**Comment by CosminBu** [comment]
I'm encountering the same problem, with different docking configurations, on Windows desktop.
It can be easily reproduced on the phone, with the original demo.

![Screenshot_2022-02-16-16-12-54-645_com android chrome](https://user-images.githubusercontent.com/59019387/154283814-d9c106e0-e37c-4457-8cc6-d9b5bab59971.jpg)
m

**Comment by jogibear9988** [comment]
I also tried on my phone (iphone 11) and could not reproduce it.
