### ISSUE TITLE
Undocked window cannot be closed

### ISSUE THREAD

**Issue by SatyaDhu** [node-projects/dock-spawn-ts#55]
how to close an undocked window? whenever we try to close the window it enables dock handles and dock it instead of closing</div>

**Comment by jogibear9988** [comment]
how do you want to close? via javascript?

**Comment by SatyaDhu** [comment]
In the UI when I drag a window and did not dock it yet but I place it on the dock handles and try clicking on close button instead of closing  it docks it for me

**Comment by SatyaDhu** [comment]
Please check this
https://user-images.githubusercontent.com/75638781/144519956-5e4cfe29-010d-4e8f-89b5-6d02b9e6e3b4.mp4

**Comment by jogibear9988** [comment]
the steering.cpp has no clode button. You can deactive if a window could be closed or not per item.
It only does get docked, cause you have the window in the middle of the screen where the dock indicator apears when you move the window

**Comment by jogibear9988** [comment]
see: https://github.com/node-projects/dock-spawn-ts/blob/e158c7a1b907be05405ef068d68120753b72c6d4/page/demo/ide/demo.js#L119

the true/false in the two lines...

**Comment by SatyaDhu** [comment]
Is there a way I don't activate the dock indicators when I click on close button.

**Comment by SatyaDhu** [comment]
> "), dockManager, null, PanelType.document, false);

this helps me remove the close button, but the use case I'm working is I should be able to close the window.

**Comment by jogibear9988** [comment]
the problem you showed me: the dialog had no close button.
so i don't know what you mean.
show me a example with a closable dialog wich then is docked, then i maybe understand whats wrong

**Comment by jogibear9988** [comment]
is now fixed :-)
thx

**Comment by SatyaDhu** [comment]
> is now fixed :-) thx

I'm not able to close the dialog instead docking

**Comment by jogibear9988** [comment]
maybe you need to refresh your browser cache...

**Comment by jogibear9988** [comment]
https://watch.screencastify.com/v/8MfnpNIHYsUngwaYYXO0

**Comment by SatyaDhu** [comment]
> https://watch.screencastify.com/v/8MfnpNIHYsUngwaYYXO0

unable to access the video. Thank you so much for your time
