### ISSUE TITLE
Intercept close button for a 'Do you want to save the changes' dialog

### ISSUE THREAD

**Issue by StefanRichterHuber** [node-projects/dock-spawn-ts#59]
Is it possible to intercept clicking the close button in a panel to show something like a 'Do you want to save dialog' prior to really closing the panel?

**Comment by jogibear9988** [comment]
I'll add a callback for this. Hopefully this evening

**Comment by StefanRichterHuber** [comment]
Thank you very much for your feedback. I´m looking forward to this change.

**Comment by jogibear9988** [comment]
It's implemented and a new NPM package is released

**Comment by jogibear9988** [comment]
closePanelContainerCallback of panelcontainer or dockmanager
