### ISSUE TITLE
async breaks ES5 compatibility

### ISSUE THREAD

**Issue by achimmihca** [node-projects/dock-spawn-ts#60]
I am evaluating this lib for my project.
Thereby, I encountered an issue in the es5 minified version: `regeneratorRuntime is not defined`

Indeed, the [file](https://github.com/node-projects/dock-spawn-ts/blob/master/lib/es5/dock-spawn-ts.js) contains a reference to `regeneratorRuntime`.
From my findings, this is a compatibility layer for async/await introduced by babel (or webpack, not sure).

Luckily, there is only a single use of async in `PanelContainer.ts`, introduced by commit d74fe1a90a762a27b7567665611cdf6e3d054ba6

After downgrading to 2.301, the issue is gone, because there is no use of async/await in this version.

Please verify whether `async` is required in this project. Maybe a callback or Promise would be an alternative?
If it is indeed required, please change the ES5 code generation to include all dependencies.

**Comment by jogibear9988** [comment]
Do we really need the ES5 build? Why and how do you use ES5?
Normally most people who use ES5, already use a bundler, so they could include dockspawn via ESM modules and the bundler will transpile.

**Comment by achimmihca** [comment]
I don't need it.
I guess the solution then is to remove es5 specific stuff altogether.
