### ISSUE TITLE
demo_simple_es5.html does not work correctly

### ISSUE THREAD

**Issue by mrgreen8** [node-projects/dock-spawn-ts#62]
after loading the application, this demo does not work correctly:
http://127.0.0.1:8080/page/demo/demo_simple_es5.html

browser issues:
dock-spawn-ts.js:1 Uncaught ReferenceError: regeneratorRuntime is not defined
    at dock-spawn-ts.js:1:20198
    at dock-spawn-ts.js:1:21001
    at dock-spawn-ts.js:1:21185
    at dock-spawn-ts.js:1:101970
(anonymous) @ dock-spawn-ts.js:1
(anonymous) @ dock-spawn-ts.js:1
(anonymous) @ dock-spawn-ts.js:1
(anonymous) @ dock-spawn-ts.js:1
demo_simple_es5.html:26 Uncaught TypeError: Cannot read properties of undefined (reading 'DockManager')
    at window.onload (demo_simple_es5.html:26:47)

**Comment by jogibear9988** [comment]
online it works: https://node-projects.github.io/dock-spawn-ts/page/demo/demo_simple_es5.html
