### ISSUE TITLE
Exception when dragging a tab which was docked "fill"

### ISSUE THREAD

**Issue by akapfham** [node-projects/dock-spawn-ts#66]
When undocking/dragging a tab which was docked in "fill" mode exceptions are raised in DockManager::_requestTabReorder.
The call to methode _findNodeFromContainer return "null".
The error is reproducible in de IDE demo (see attached screen shots).

![demo-gui](https://user-images.githubusercontent.com/55833964/195031433-0a95cff7-8c14-4970-99f5-07fa1811ab57.png)
![console_output](https://user-images.githubusercontent.com/55833964/195031467-69a5bd52-adba-4c79-b761-a3b673642bcd.png)

**Comment by jogibear9988** [comment]
I also saw this yesterday in the ide, but have not yet an idea whats causing it.
don't know when I will have time to look for it, but atm. it does not stop it from beeing usable

**Comment by jogibear9988** [comment]
seems to be fixed in current master

**Comment by akapfham** [comment]
Thank you!

**Comment by akapfham** [comment]
I just updated to 2.511.0 and the exception is still there! You get the same exception with the IDE-Demo (https://node-projects.github.io/dock-spawn-ts/page/demo/ide/demo.html). Though i do not know if the Demo is already updated to 2.511.0.
![error_2 511](https://user-images.githubusercontent.com/55833964/207000236-9f264280-4038-437a-92f0-7ae21c2328ab.png)
