### ISSUE TITLE
Setting the active panel does not work

### ISSUE THREAD

**Issue by akapfham** [node-projects/dock-spawn-ts#67]
Setting the active panel via this.dockManager.activePanel = newActivePanel does not work. The GUI does not reflect the changes.
In the IDE demo lets say you want to set the "Outline" tab as the active tab and not "Solution Explorer" but you want the order of the tabs exactly as they are, how can this be achived? Setting this.dockManager.activePanel does not work.
![active-tab-gui](https://user-images.githubusercontent.com/55833964/195032906-917d209a-2cb9-475a-9e71-1962961cf31d.png)

**Comment by jogibear9988** [comment]
I do it in my app like this:

       propertyGridNode.parent.container.setActiveChild(propertyGridNode.container);

the activePanel at the moment is only set from inside of dockspawn. writing it does not have any effects.

**Comment by akapfham** [comment]
Thank you! This works perfectly.
