### ISSUE TITLE
Possible to use as a standalone library?

### ISSUE THREAD

**Issue by abalter** [node-projects/dock-spawn-ts#76]
Would it be possible to package the various files in `/lib/js` into a single library that can be imported---e.g. jquery?

**Comment by jogibear9988** [comment]
it is look here: https://www.npmjs.com/package/dock-spawn-ts

**Comment by abalter** [comment]
Sorry, I meant that everything you need to import is in one file.

```
<html>
<head>
    <script src=".........../dock-spawn.min.js">
...
...
...
```

Currently, there are just a few files to import in the main app, but those then refer to others in the directory tree.

**Comment by jogibear9988** [comment]
look in the es5 directory

**Comment by abalter** [comment]
Thanks!
