### ISSUE TITLE
Example code is not working

### ISSUE THREAD

**Issue by KestutisMa** [node-projects/dock-spawn-ts#77]
Hi, yours component looks nice, but original example code from readme is not working (not adding title bar and close button).
Code: https://codesandbox.io/s/dock-spawn-ts-problem-m29iqp?file=/src/index.ts
Also described in reddit: https://www.reddit.com/r/learnjavascript/comments/zl19tc/ui_for_biophysical_modeling_app_my_simple_code_is/

Where problem could be?

**Comment by jogibear9988** [comment]
Where do you load the css from dockspawn?

**Comment by jogibear9988** [comment]
<head>
            <link rel="stylesheet" href="node_modules/dock-spawn-ts/lib/css/dock-manager.css">
            <link rel="stylesheet" href="node_modules/dock-spawn-ts/lib/css/dock-manager-style.css">  
        </head>

**Comment by KestutisMa** [comment]
thanks @jogibear9988 it works! but this is not mentioned in https://github.com/node-projects/dock-spawn-ts/blob/master/README.md

**Comment by jogibear9988** [comment]
maybe you could fix the doc and create a pull req?
