### ISSUE TITLE
Minimal example using the es5 module

### ISSUE THREAD

**Issue by abalter** [node-projects/dock-spawn-ts#78]
Would you be willing to create a minimal example using the es5 module?

[This](https://codesandbox.io/s/dock-spawn-self-contained-demo-kufujt) is what I tried, but it did not work.

It's based on the [demo-simple](https://github.com/node-projects/dock-spawn-ts/blob/master/page/demo/demo_simple.html) demo.

**Comment by jogibear9988** [comment]
Look in the browsers network tab:

<img width="966" alt="image" src="https://user-images.githubusercontent.com/364896/212533570-00f5e2da-b5a1-4e5c-8f1b-ce1ee325fc4a.png">

the javscript is not loaded from github. I don't know why, but it's not a dockspawn issue.

**Comment by jogibear9988** [comment]
If you also look at my simple demo: https://node-projects.github.io/dock-spawn-ts/page/demo/demo_simple.html
It works. So the error seems to be a codesandbox

**Comment by abalter** [comment]
I don't think you understand what I mean. For example, could make a codepen or JS Fiddle? O a single HTML file that contains a demo?

Here are some examples from other UI libraries:

Minimal example using the es5 module · Issue #78 · node-projects/dock-spawn-ts
https://github.com/node-projects/dock-spawn-ts/issues/78

webix jsfiddle - Google Search
https://www.google.com/search?q=webix+jsfiddle&client=firefox-b-1-d&sxsrf=AJOqlzXG0_1sOd2UI9BXGyMD_IA1N2r2AQ%3A1673817979922&ei=e2_EY6j3N7XD9AOjuL4g&ved=0ahUKEwjooPLwwcr8AhW1IX0KHSOcDwQQ4dUDCA8&uact=5&oq=webix+jsfiddle&gs_lcp=Cgxnd3Mtd2l6LXNlcnAQAzIFCCEQoAE6CggAEEcQ1gQQsAM6BQgAEIAEOgYIABAWEB46CAgAEBYQHhAKSgQIQRgASgQIRhgAUN4DWLsQYI0SaAJwAXgAgAGOAogBkQmSAQUxLjYuMZgBAKABAcgBA8ABAQ&sclient=gws-wiz-serp

W2UI Demo: combo/2 - JSFiddle - Code Playground
https://jsfiddle.net/api/post/library/pure/

easyui Tabs
https://codepen.io/ChrisAirpac/pen/GRrrOr

webix price
https://codepen.io/Fullzero/pen/yJJpVP

Webix - Layout
https://codepen.io/sunilnanda/pen/mEgmdY

GoldenLayout Blueprintjs Table React - CodeSandbox
https://codesandbox.io/s/goldenlayout-blueprintjs-table-react-unf72

Golden Layout save/load states
https://codepen.io/JoeHastings/pen/EWGbNO

**Comment by jogibear9988** [comment]
I understand what you mean.

But as I showed in my screenshot, the browser downloads a empty JS, so it could not work.

I also tried to reference the npm module in codesandbox, and it did not work, but I also don't know why.
Codesandbox wraps it's javascript in some othe JS.

But if you look at my sample you see that the library works

**Comment by jogibear9988** [comment]
Look at this, this works:

https://jsfiddle.net/r39gup51/

**Comment by abalter** [comment]
Those don't dock.

**Comment by jogibear9988** [comment]
for me it works: https://watch.screencastify.com/v/IVOLwUL7fTy92zeupSLd

**Comment by abalter** [comment]
Sorry. You are right. It does.

**Comment by abalter** [comment]
I'll play around with it. I'd like to be able to implement the full IDE example that way.

It looks like you were probably inspired by JQ Widgets.

https://www.jqwidgets.com/jquery-widgets-documentation/documentation/jqxdockinglayout/jquery-docking-layout-getting-started.htm?search=

https://codepen.io/abalter/pen/wvxqPzZ

**Comment by jogibear9988** [comment]
If you're looking for more examples, my designer component demo also uses it: https://node-projects.github.io/web-component-designer-demo/index.html

**Comment by abalter** [comment]
Yes. I think that is very cool. I want to build an IDE along the lines of RStudio or Matlab.
