### ISSUE TITLE
How to programmatically select a panel ?

### ISSUE THREAD

**Issue by nmadrane** [node-projects/dock-spawn-ts#79]
Hi,

Could you tell me please how to programmatically select a panel ?
Here is what I tried :

```
mypanel= new PanelContainer(......);
.......
dockManager.activePanel = mypanel;
```

But it doesn't change anything. 

Thanks

Nabil

**Comment by jogibear9988** [comment]
for example, I do it like this...

      let propertyGridNode = dockManager.getNodeByElementId('propertyGrid')
      propertyGridNode.parent.container.setActiveChild(propertyGridNode.container);

**Comment by nmadrane** [comment]
Thanks a lot, it works.

Nabil
