### ISSUE TITLE
Right clicking on panel tabs shouldn't open the "Close all documents" contextual menu

### ISSUE THREAD

**Issue by NitnerocL** [node-projects/dock-spawn-ts#80]
### Steps to reproduce
1. Go to the [IDE demo](https://node-projects.github.io/dock-spawn-ts/page/demo/ide/demo.html)
2. Right click on the "Solution Explorer" / "Outline" tabs int the left panel

### Actual behavior
The contextual menu "Close all documents" / "- but this" opens
![image](https://github.com/node-projects/dock-spawn-ts/assets/15650417/ce1d9979-9964-4da9-a3f4-a955f246b282)

### Expected behavior
Nothing should happen

### Remarks
These buttons are related to the documents in the main editor, not the side panels. In fact, clicking on them will close the center documents and not the panels, which is misleading

**Comment by jogibear9988** [comment]
yeah, you are right. Could you create a pull req. to fix this?

**Comment by NitnerocL** [comment]
Hi, I have just created one :)
