### ISSUE TITLE
dialog content will be removed if re-opened dialog after closed it

### ISSUE THREAD

**Issue by CSDotNET0211** [node-projects/dock-spawn-ts#85]
this issue is happened not only Dock Spawn IDE Demo but also my project.
after that, docking to something and undocking to fix.
see Output window what I did.
![image](https://github.com/node-projects/dock-spawn-ts/assets/59834175/d231ed21-eb70-4df1-a697-59ee26c6c3e0)

**Comment by jogibear9988** [comment]
I'll have also seen this.
Seems to have occured after our big refactoring wich does not remove the windows from the DOM any more.
I'll work on this, but it will take a little bit of time, as I'm currently in other projects. Hopefully I get to this at the end ob february.
I'm also at the moment reworking the whole component, to support undock to extra windows, where i've also seen this issue

**Comment by CSDotNET0211** [comment]
thank you for your response.
okey I will be wait patiently

**Comment by jogibear9988** [comment]
should be fixed
