### ISSUE TITLE
can lock panel resizing and docking

### ISSUE THREAD

**Issue by madkne** [node-projects/dock-spawn-ts#88]
Hi,
Can I Lock A Panel that can not resize Panel or change docking or change state to floating window

for edit mode environment needed

Thanks
@jogibear9988 @ampam @ribbanya @7evenk

**Comment by jogibear9988** [comment]
Only for the Dialog a no resize is possible atm.
And the PanelContainer has a canUndock function with wich you can modify the canundock state.

But if you need a non resizable panel, you could create a fixed div outside of dockspawn.

**Comment by madkne** [comment]
Thanks
