### ISSUE TITLE
Add an option to enable/disable opening in a new browser window

### ISSUE THREAD

**Issue by NitnerocL** [node-projects/dock-spawn-ts#90]
Hi, is it possible to add an option to disable the display of the "open in new window" menu? 

This new feature is great but isn't useable as is in my app: I'm using VueJS but the styles and script are not forwarded correctly to the new window, plus I would have to redesign entierly state sharing between my panels so that they can communicate across multiple windows. Defining this feature as optional opt-in would avoid these breaking changes and allow a smoother migration.

**Comment by jogibear9988** [comment]
Yeah, for sure.
Could you create an option? If not I will do, but I'm nor sure if I've time this week.

**Comment by jogibear9988** [comment]
option should be in:

      https://github.com/node-projects/dock-spawn-ts/blob/master/src/DockConfig.ts

I think default should be true

**Comment by NitnerocL** [comment]
Ok I will do it

**Comment by jogibear9988** [comment]
thx
